[package]
name = "uefi_bin_enum"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi = { version = "0.17.0", features = ["exts"] }
uefi-services = "0.14.0"
bitflags = "1.3.1"
log = { version = "0.4.5", default-features = false }
ucs2 = "0.3.2"
uefi-macros = "0.8.0"


[workspace]
